// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.2
// source: goo_cel_play/type.proto

package goo_cel_play

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goo_cel_play_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_goo_cel_play_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_goo_cel_play_type_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RequestContext) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_goo_cel_play_type_proto protoreflect.FileDescriptor

var file_goo_cel_play_type_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x6f, 0x6f, 0x5f, 0x63, 0x65, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x70, 0x6c, 0x61, 0x79, 0x32,
	0x30, 0x32, 0x32, 0x2e, 0x67, 0x6f, 0x6f, 0x5f, 0x63, 0x65, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x22, 0x3c, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x0f,
	0x5a, 0x0d, 0x67, 0x6f, 0x6f, 0x5f, 0x63, 0x65, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goo_cel_play_type_proto_rawDescOnce sync.Once
	file_goo_cel_play_type_proto_rawDescData = file_goo_cel_play_type_proto_rawDesc
)

func file_goo_cel_play_type_proto_rawDescGZIP() []byte {
	file_goo_cel_play_type_proto_rawDescOnce.Do(func() {
		file_goo_cel_play_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_goo_cel_play_type_proto_rawDescData)
	})
	return file_goo_cel_play_type_proto_rawDescData
}

var file_goo_cel_play_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_goo_cel_play_type_proto_goTypes = []interface{}{
	(*RequestContext)(nil), // 0: play2022.goo_cel_play.requestContext
}
var file_goo_cel_play_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goo_cel_play_type_proto_init() }
func file_goo_cel_play_type_proto_init() {
	if File_goo_cel_play_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goo_cel_play_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goo_cel_play_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goo_cel_play_type_proto_goTypes,
		DependencyIndexes: file_goo_cel_play_type_proto_depIdxs,
		MessageInfos:      file_goo_cel_play_type_proto_msgTypes,
	}.Build()
	File_goo_cel_play_type_proto = out.File
	file_goo_cel_play_type_proto_rawDesc = nil
	file_goo_cel_play_type_proto_goTypes = nil
	file_goo_cel_play_type_proto_depIdxs = nil
}
